### ISSUE TITLE
check_cassandra_balance.pl issue : uninitialized value $percentage

### ISSUE THREAD

**Issue by floppy84** [HariSekhon/nagios-plugins#100] opened 2016-06-03 09:09 UTC
Hi,

I got another issue but on balance plugin ::

verbose mode on

check_cassandra_balance.pl version 0.5.1  =>  Hari Sekhon Utils version 1.18.1

nodetool:                 nodetool
host:                     cav-dev-esccorcsd-1
port:                     7199
user:                     cassandra
password:                 <omitted>
warning  upper:           10
critical upper:           20

setting timeout to 10 secs

fetching cluster nodes information
cmd: /usr/bin/nodetool --host '10.70.8.59' --port '7199' --username 'cassandra' --password '*******' status
output:

Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load       Tokens       Owns    Host ID                               Rack
UN  10.70.8.59  15.17 GB   256          ?       6cfd4702-61e1-4f97-8f70-fc890ceac924  rack1

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless

exitcode: 0

Use of uninitialized value $percentage in string eq at ./check_cassandra_balance.pl line 76.
Use of uninitialized value $percentage in numeric gt (>) at ./check_cassandra_balance.pl line 79.
Use of uninitialized value $percentage in numeric lt (<) at ./check_cassandra_balance.pl line 82.
checking thresholds

OK: 0.00% max imbalance between 1 cassandra node (w=10/c=20), max node: 0% [uninitialized_node (uninitialized_rack)], min node: 0% [uninitialized_node (uninitialized_rack)] | 'max_%_imbalance'=0.00%;10;20;

**Comment by HariSekhon** [comment] 2016-06-03 10:41
This was caused by cassandra returning '?' for the token ownership %.

This used to be correctly handled before but a change introduced a bug. I've pushed a fix for it but be aware that the fix will only catch the scenario to return UNKNOWN as there is no way of calculating the cluster balance if cassandra itself doesn't know the token % owernship and reports '?' instead of the percentage.

**Closed by HariSekhon** 2016-06-03 10:41 UTC
