### ISSUE TITLE
check_memcached_stats.pl

### ISSUE THREAD

**Issue by rmalenko** [HariSekhon/nagios-plugins#90] opened 2016-03-23 16:17 UTC
Hello Hari,

I have run check_memcached_stats.pl -H localhost -P 11211 -w 100 -c 150 -vvv
and get message
CRITICAL: unrecognized line in output: 'STAT version 1.4.14 (Ubuntu)'

could you prompt me what it does mean, please?

**Comment by HariSekhon** [comment] 2016-03-23 17:18
Hi @rmalenko 

Thanks for raising this ticket.

The is caused by the additional "(Ubuntu)" information at the end of the version breaking the standard format for the memcached version.

I've just added a fix to work around it, please ```git pull``` and try again.

Thanks

Hari

**Comment by rmalenko** [comment] 2016-03-24 11:12
Hi Hari,
Thank you. It works fine now.

**Comment by HariSekhon** [comment] 2016-03-24 11:45
Cool, thanks for confirming, I'll close this ticket.

**Closed by HariSekhon** 2016-03-24 11:45 UTC
Labels: enhancement
