### ISSUE TITLE
check_kafka.pl plugin not working (not initiating traffic)

### ISSUE THREAD

**Issue by dpriscornic** [HariSekhon/nagios-plugins#93] opened 2016-04-15 12:55 UTC
Hello,

Nagios server CentOS 6.5, Nagios Core 3.5.1, perl v5.10.1, Kafka 0.8012
Kafka running on 10.11.5.45, listening on 9092.

Tcpdump on Nagios server during the run shows no traffic from nagios host to 10.11.5.45 on tcp 9092

[root@nagios02 ~]#  /usr/local/nagios/libexec/nagios-plugins/check_kafka.pl -H 10.11.5.45 -vv 
verbose mode on

host:                     10.11.5.45
port:                     9092
partition:                0
required acks:            1
send-max-attempts:        1
receive-max-attempts:     1
retry-backoff:            200
sleep:                    0.5

setting timeout to 10 secs

connecting to Kafka broker at 10.11.5.45:9092
connecting producer
connecting consumer

CRITICAL: Error: Can't get metadata: topic = 'nagios'

[root@nagios02 ~]#  /usr/local/nagios/libexec/nagios-plugins/check_kafka.pl -H 10.11.5.45 -v -v --list-topics
verbose mode on

host:                     10.11.5.45
port:                     9092
partition:                0
required acks:            1
send-max-attempts:        1
receive-max-attempts:     1
retry-backoff:            200
sleep:                    0.5

setting timeout to 10 secs

connecting to Kafka broker at 10.11.5.45:9092
CRITICAL: failed to get metadata, broker offline or wrong port? (some deployments use 9092, some such as Hortonworks use 6667)

Any idea what am I doing wrong?

Thank you.

**Comment by HariSekhon** [comment] 2016-04-15 13:26
@dpriscornic 

Can you show me the tcpdump command line you're using, it's possible that you are listening on the wrong interface (```-i any``` could be useful), or it could be a routing issue where the traffic isn't able to send it out of an interface if it doesn't have a route to the target network. Can you check with netcat to the Kafka port and test the networking is working correctly?

**Comment by dpriscornic** [comment] 2016-04-15 13:38
Hello,

Thank you for your fast response.

[root@nagios02.woow.toronto ~]#  /usr/local/nagios/libexec/nagios-plugins/check_kafka.pl -H 10.11.5.45 -vv 
verbose mode on

host:                     10.11.5.45
port:                     9092
partition:                0
required acks:            1
send-max-attempts:        1
receive-max-attempts:     1
retry-backoff:            200
sleep:                    0.5

setting timeout to 10 secs

connecting to Kafka broker at 10.11.5.45:9092
connecting producer
connecting consumer

CRITICAL: Error: Can't get metadata: topic = 'nagios'
[root@nagios02.woow.toronto ~]# telnet 10.11.5.45 9092
Trying 10.11.5.45...
Connected to 10.11.5.45.
Escape character is '^]'.
^]
telnet> quit
Connection closed.
[root@nagios02.woow.toronto ~]# mtr -c 3 -r 10.11.5.45
HOST: nagios02.woow.toronto       Loss%   Snt   Last   Avg  Best  Wrst StDev
  1. 10.11.5.45                    0.0%     3    0.8   0.9   0.8   0.9   0.0
[root@nagios02.woow.toronto ~]# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
10.11.1.0       0.0.0.0         255.255.255.0   U     0      0        0 eth0
169.254.0.0     0.0.0.0         255.255.0.0     U     1002   0        0 eth0
0.0.0.0         10.11.1.1       0.0.0.0         UG    0      0        0 eth0
[root@nagios02.woow.toronto ~]# 

[root@nagios02.woow.toronto ~]# tcpdump -nnei eth0 port 9092 
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 65535 bytes
^C
0 packets captured
0 packets received by filter
0 packets dropped by kernel
[root@nagios02.woow.toronto ~]# 

The same dump displays the traffic when I run telnet.

Thank you,

**Comment by HariSekhon** [comment] 2016-04-15 13:43
Try with more triple verbosity and debug output:

```-v -v -v -D```

This should get the Kafka library to output more as well.

**Comment by dpriscornic** [comment] 2016-04-15 13:47
[root@nagios02.woow.toronto ~]#  /usr/local/nagios/libexec/nagios-plugins/check_kafka.pl -H 10.11.5.45 -v -v -v -D
2016-04-15 13:47:34 +0000  verbose mode on

2016-04-15 13:47:34 +0000  check_kafka.pl version 0.2.2  =>  Hari Sekhon Utils version 1.18.1

2016-04-15 13:47:34 +0000  host:                     10.11.5.45
2016-04-15 13:47:34 +0000  port:                     9092
2016-04-15 13:47:34 +0000  partition:                0
2016-04-15 13:47:34 +0000  required acks:            1
2016-04-15 13:47:34 +0000  send-max-attempts:        1
2016-04-15 13:47:34 +0000  receive-max-attempts:     1
2016-04-15 13:47:34 +0000  retry-backoff:            200
2016-04-15 13:47:34 +0000  sleep:                    0.5
2016-04-15 13:47:34 +0000  
2016-04-15 13:47:34 +0000  setting timeout to 10 secs

2016-04-15 13:47:34 +0000  connecting to Kafka broker at 10.11.5.45:9092
2016-04-15 13:47:34 +0000  $VAR1 = bless( {
                 '_IO_cache' => {
                                  '10.11.5.45:9092' => {
                                                         'NodeId' => undef,
                                                         'IO' => undef,
                                                         'port' => '9092',
                                                         'host' => '10.11.5.45'
                                                       }
                                },
                 '_metadata' => {},
                 'MaxLoggedErrors' => 100,
                 'AutoCreateTopicsEnable' => 0,
                 'broker_list' => [],
                 'SEND_MAX_ATTEMPTS' => '1',
                 'port' => 9092,
                 'host' => '10.11.5.45',
                 '_nonfatal_errors' => [],
                 '_leaders' => {},
                 'timeout' => '1.5',
                 'RETRY_BACKOFF' => '200',
                 'RECEIVE_MAX_ATTEMPTS' => 4,
                 'CorrelationId' => -346088833
               }, 'Kafka::Connection' );

CRITICAL: failed to get metadata, broker offline or wrong port? (some deployments use 9092, some such as Hortonworks use 6667)
[root@nagios02.woow.toronto ~]#

**Comment by HariSekhon** [comment] 2016-04-25 10:36
Apologies for the slowness on this, I'm really busy on several fronts and will try to get time to look at this within 2 weeks.

**Comment by dpriscornic** [comment] 2016-04-25 13:29
Thank you! I am looking forward for your reply.

**Comment by HariSekhon** [comment] 2016-05-03 20:12
I've just tested this using the accompanying dockerized test which indicates that it's working - if you have docker can you try the test and see what it says:

```
tests/test_kafka.sh

# ============================================================================ #
#                                   K a f k a
# ============================================================================ #

using docker address '192.168.99.100'
Setting up Apache Kafka test container
====================
Starting Docker Kafka_scala-2.10 test container
5a23f4ae41d1b03124cda24c1203bf3b6ada54be203b503ee952da9ca74f9721
waiting 20 seconds for Kafka to start up and settle
        creating Kafka test topic
        Created topic "nagios-plugins-test".
====================
Topics:

nagios-plugins-test
====================
OK: message returned successfully by Kafka broker at 192.168.99.100:9092
====================

Deleting container nagios-plugins-kafka
```

**Comment by HariSekhon** [comment] 2016-05-12 16:01
@dpriscornic 

I've pushed a Python version of this Kafka plugin that I've had lying around for 2-3 months - you can try that as well to check if it really is a code or environment issue. It also passes the accompanying Dockerized test.

**Comment by HariSekhon** [comment] 2016-05-19 14:39
@dpriscornic 

Did you get a chance to get the Python version instead? That will differentiate between it being a code problem or a networking / environment problem.

Since I can't reproduce this if I don't hear back from you I'll have to close this ticket.

**Comment by dpriscornic** [comment] 2016-05-20 15:20
I am sorry, I was on vacation, didn't get to test. I will test next week and get back to you. Thank you!

**Comment by dpriscornic** [comment] 2016-05-23 07:46
Hello Hari,

Thank you a lot! The Python version is working like a charm:

OK: Kafka message published and consumed back successfully, published in 0.2135210 secs, consumed in 0.0452490 secs | publish_time=0.2135210s;1;2 consume_time=0.0452490s;1;2

Thank you so so much!

**Comment by HariSekhon** [comment] 2016-05-23 08:38
Ok, did you get a chance to run the ```tests/test_kafka.sh```?

I've just had a thought, I wonder if the perl version is picking up something from the environment like a proxy environment variable... would be good if you have docker and got a chance to run the test script because that should make it clear if the code has an obvious bug relating to your original connection problem as I cannot reproduce that.

**Comment by dpriscornic** [comment] 2016-05-23 11:39
No, I will give it a try tomorrow or the day after and get back to you.

Thank you!

**Comment by dpriscornic** [comment] 2016-06-01 12:46
Hello,

Here is the result of the dockerized test:

[root@nagios02.woow.toronto nagios-plugins_2016_05_20]# tests/test_kafka.sh 

# ============================================================================ #
#                                   K a f k a
# ============================================================================ #

Setting up Apache Kafka test container
====================
using docker address ''
starting container: Unable to find image 'harisekhon/kafka:latest' locally
latest: Pulling from harisekhon/kafka
cacc99976415: Pull complete 
5b66679e02f4: Pull complete 
1f8c9c887b89: Pull complete 
f0dc6e5bff03: Pull complete 
49be0a427949: Pull complete 
ca9ef0227c5b: Pull complete 
44e14cfaaf9e: Pull complete 
4abc458b2d81: Pull complete 
fe48984ff4aa: Pull complete 
e24da00e1ee9: Pull complete 
bb1e08691c94: Pull complete 
82cb3a435085: Pull complete 
59e6909bc3c1: Pull complete 
bf620d4d7ff0: Pull complete 
5a67c94d7d60: Pull complete 
Digest: sha256:9a15cfd2183135c61659506f416ba1801efe88ef404647393ca5d4e7ac02648a
Status: Downloaded newer image for harisekhon/kafka:latest
8f6b879b52c29398bd963b8ac54eac3093d7cb89bd24af57e99d4428ff1d932f
====================
Running containers:
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS                  PORTS                              NAMES
8f6b879b52c2        harisekhon/kafka    "/bin/sh -c 'zookeep   2 seconds ago       Up Less than a second   2181/tcp, 0.0.0.0:9092->9092/tcp   nagios-plugins-kafka-test   
====================
waiting 20 seconds for container to fully initialize...
====================
creating Kafka test topic
Created topic "nagios-plugins-kafka-test".
====================
Kafka Topics:

UNKNOWN: [Errno -2] Name or service not known
====================
Kafka topic 'nagios-plugins-kafka-test' partitions:

UNKNOWN: [Errno -2] Name or service not known
====================
UNKNOWN: [Errno -2] Name or service not known
====================
UNKNOWN: [Errno -2] Name or service not known
You have new mail in /var/spool/mail/root
[root@nagios02.woow.toronto nagios-plugins_2016_05_20]# 

I tried to manually check the docker container, the same result as before:

[root@nagios02.woow.toronto nagios-plugins_2016_05_20]# docker ps
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS                              NAMES
8f6b879b52c2        harisekhon/kafka    "/bin/sh -c 'zookeep   2 minutes ago       Up 2 minutes        0.0.0.0:9092->9092/tcp, 2181/tcp   nagios-plugins-kafka-test   
[root@nagios02.woow.toronto nagios-plugins_2016_05_20]# netstat -tlnp | grep 9092
tcp        0      0 :::9092                     :::*                        LISTEN      19766/docker-proxy  
[root@nagios02.woow.toronto nagios-plugins_2016_05_20]# telnet 127.0.0.1 9092
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
^]
telnet> quit
Connection closed.
[root@nagios02.woow.toronto nagios-plugins_2016_05_20]# /usr/local/nagios/libexec/harisekhon/nagios-plugins/check_kafka.pl -H 127.0.0.1 -vvv
verbose mode on

check_kafka.pl version 0.2.1  =>  Hari Sekhon Utils version 1.16.5

host:                     127.0.0.1
port:                     9092
partition:                0
required acks:            1
send-max-attempts:        1
receive-max-attempts:     1
retry-backoff:            200
sleep:                    0.5

setting timeout to 10 secs

connecting to Kafka broker at 127.0.0.1:9092
CRITICAL: failed to get metadata, broker offline or wrong port? (some deployments use 9092, some such as Hortonworks use 6667)
[root@nagios02.woow.toronto nagios-plugins_2016_05_20]# /usr/local/nagios/libexec/harisekhon/nagios-plugins_2016_05_20/check_kafka.pl -H 127.0.0.1 -T nagios -vvv
verbose mode on

check_kafka.pl version 0.2.3  =>  Hari Sekhon Utils version 1.18.1

host:                     127.0.0.1
port:                     9092
topic:                    nagios
partition:                0
required acks:            1
send-max-attempts:        1
receive-max-attempts:     1
retry-backoff:            200
sleep:                    0.5

setting timeout to 10 secs

connecting to Kafka broker at 127.0.0.1:9092
CRITICAL: failed to get metadata, broker offline or wrong port? (some deployments use 9092, some such as Hortonworks use 6667)
[root@nagios02.woow.toronto nagios-plugins_2016_05_20]# 

There is a high chance that the issue is caused by my environment.
That nagios server was installed some time ago, it runt CentOS 6.5 and the perl modules were installed, over time, both via cpan and yum packages.

Again, than you very much for the python version of the plugin!

**Comment by HariSekhon** [comment] 2016-06-01 15:21
Yes that does look like there is something strange in the environment. The only thing I can think of is that there is some issue with the perl modules or the environment or something. I can't reproduce that but as the Python version works and the Perl version works in the Dockerized tests I'll have to assume it's a local problem.

**Closed by HariSekhon** 2016-06-01 15:21 UTC
