### ISSUE TITLE
check_yum fails to run successful

### ISSUE THREAD

**Issue by jdfeathe** [HariSekhon/Nagios-Plugins#393] opened 2022-09-06 17:52 UTC
So far, I've only tested this on RHEL 7. Downloaded direct from git only change was to permissions (0644 to 0755). I've attached the full verbose run. Ends with:

No packages needed for security; 0 packages available
Security: kernel-3.10.0-1160.76.1.el7.x86_64 is an installed security update
Security: kernel-3.10.0-1160.6.1.el7.x86_64 is the currently running version
'
output lines not accounted for: ['Security: kernel-3.10.0-1160.76.1.el7.x86_64 is an installed security update', 'Security: kernel-3.10.0-1160.6.1.el7.x86_64 is the currently running version']
YUM WARNING: Yum output signature (1 unique lines) is larger than number of total updates (0). Please make sure you have upgraded to the latest version from https://github.com/HariSekhon/Nagios-Plugins. If the problem persists, please raise a ticket at https://github.com/HariSekhon/Nagios-Plugins/issues with the full -vvv output

[check_yum.txt](https://github.com/HariSekhon/Nagios-Plugins/files/9499578/check_yum.txt)

**Comment by powerflo23** [comment] 2022-09-07 07:22
I have the same problem on RHEL7.9 -> 3.10.0-1160.71.1.el7.x86_64

....
 --> sssd-common-pac-1.14.0-43.el7_3.11.x86_64 from rhel-7-server-rpms excluded (updateinfo)
No packages needed for security; 0 packages available
Security: kernel-3.10.0-1160.76.1.el7.x86_64 is an installed security update
Security: kernel-3.10.0-1160.71.1.el7.x86_64 is the currently running version
Uploading Enabled Repositories Report
Loaded plugins: priorities, product-id, subscription-manager
'
output lines not accounted for: ['Security: kernel-3.10.0-1160.76.1.el7.x86_64 is an installed security update', 'Security: kernel-3.10.0-1160.71.1.el7.x86_64 is the currently running version']
YUM WARNING: Yum output signature (1 unique lines) is larger than number of total updates (0). Please make sure you have upgraded to the latest version from https://github.com/HariSekhon/Nagios-Plugins. If the problem persists, please raise a ticket at https://github.com/HariSekhon/Nagios-Plugins/issues with the full -vvv output

The Problem ist only with the option -W. No Problem with the option -A

Nagios Plugin for Yum updates on RedHat/CentOS systems - Version 0.12.6
Author: Hari Sekhon

setting plugin timeout to 30 seconds
running command: /usr/bin/yum check-update
Returncode: '0'
Output: 'Loaded plugins: changelog, enabled_repos_upload, package_upload, priorities,
              : product-id, search-disabled-repos, subscription-manager
825 packages excluded due to repository priority protections
Security: kernel-3.10.0-1160.76.1.el7.x86_64 is an installed security update
Security: kernel-3.10.0-1160.71.1.el7.x86_64 is the currently running version
Uploading Enabled Repositories Report
Loaded plugins: priorities, product-id, subscription-manager
'
YUM WARNING: Kernel security update is installed but requires a reboot

On RHEL8 no problems
./new.py
YUM CRITICAL: Kernel security update is installed but requires a reboot
./new.py -W
YUM CRITICAL: Kernel security update is installed but requires a reboot
./new.py -A
YUM WARNING: Kernel security update is installed but requires a reboot

**Comment by HariSekhon** [comment] 2022-09-09 18:12
I've just pushed a fix, please git pull and try version 0.12.7.

**Comment by jdfeathe** [comment] 2022-09-09 18:55
I had to change DEFAULT_TIMEOUT from 30 to 60 on my server but this works now. Thank you!!

**Comment by HariSekhon** [comment] 2022-09-14 10:28
Thanks for confirming.

The `-t / --timeout` switch means you shouldn't need to edit the `DEFAULT_TIMEOUT` in the code, but it's up to you.

**Closed by HariSekhon** 2022-09-14 10:28 UTC
Labels: software update required
