### ISSUE TITLE
Panic error

### ISSUE THREAD

**Issue by roaldle** [HariSekhon/nagios-plugins#128] opened 2017-01-08 23:50 UTC
I get a panic error on the last version of the image. 
I found a machine where I still have an old one. I executed a check, updated the image and executed again. Second time it fails because of a panic error.

```
root@solr1:~# docker run --rm --net="host" harisekhon/nagios-plugins check_solr_core.pl -H localhost -P 8983 --core ca003
OK: Solr core 'ca003' indexSize: 0.00MB, indexHeapUsage: 0.00MB, numDocs: 0, maxDoc: 0, deletedDocs: 0, segmentCount: 0, uptime: 3 days 12 hours 10 mins 42 secs, started: 2017-01-05T11:31:05.85Z, last modified: N/A, query time 267ms, QTime: 12ms | indexSize=0.00MB;;; indexHeapUsage=0.00MB;;; numDocs=0;;; maxDoc=0 deletedDocs=0 segmentCount=0 query_time=267ms;;; query_QTime=12ms


root@solr1:~# docker pull harisekhon/nagios-plugins
Using default tag: latest
latest: Pulling from harisekhon/nagios-plugins
0a8490d0dfd3: Pull complete
ce0f9a3d2da4: Pull complete
b5b201daed58: Pull complete
Digest: sha256:c1441a28cad2febe8dbdfb72ce105d2d45e9c93d323df71e6a870d38058b748f
Status: Downloaded newer image for harisekhon/nagios-plugins:latest


root@solr1:~# docker run --rm --net="host" harisekhon/nagios-plugins check_solr_core.pl -H localhost -P 8983 --core ca003
panic: standard_init_linux.go:175: exec user process caused "no such file or directory" [recovered]
	panic: standard_init_linux.go:175: exec user process caused "no such file or directory"

goroutine 1 [running, locked to thread]:
panic(0x7ea960, 0xc8201151f0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/urfave/cli.HandleAction.func1(0xc82009b2f8)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:478 +0x38e
panic(0x7ea960, 0xc8201151f0)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0xc82009ac08, 0xc82001a0d0, 0xc82009ad18)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0x136
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0xc820051630, 0x7efdfa0536b0, 0xc8201151f0)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x5b1
main.glob.func8(0xc82006ea00, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/main_unix.go:26 +0x68
reflect.Value.call(0x74f160, 0x900ae8, 0x13, 0x846e88, 0x4, 0xc82009b278, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x74f160, 0x900ae8, 0x13, 0xc82009b278, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:303 +0xb1
github.com/urfave/cli.HandleAction(0x74f160, 0x900ae8, 0xc82006ea00, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:487 +0x2ee
github.com/urfave/cli.Command.Run(0x849d38, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8dfde0, 0x51, 0x0, ...)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/command.go:191 +0xfec
github.com/urfave/cli.(*App).Run(0xc820001800, 0xc82000a100, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:240 +0xaa4
main.main()
	/go/src/github.com/opencontainers/runc/main.go:137 +0xe24
```

Similar issue:
[https://github.com/docker/docker/issues/27940#issuecomment-257957823](url)

**Comment by Raboo** [comment] 2017-01-09 10:30
This has happened before, see #121.
Perhaps it's better to start with versioned tags and have them in docker hub, so we don't have to fetch "latest" always?

**Comment by HariSekhon** [comment] 2017-01-13 15:16
@Raboo I agree.

This appears to be mainly caused by alpine build issues and changes, but it could also be caused by innocuous changes to the build scripts.

It's actually more stable if I were to use a debian or centos base image but then the image size would be much larger.

What I'll probably do is create a stable static image based on alpine which is only periodically rebuilt with the latest updates, tested and then pushed, as well as centos and debian specific builds and leave the latest build just for the CI system to test or those needing the very latest updates.

**Comment by HariSekhon** [comment] 2017-01-13 16:26
Looks like this was caused by Alpine packages dependency changes causing a dependency conflict... seems like Alpine is always breaking things in order to try to minimize their image sizes.

I'm going to add centos, debian and ubuntu builds, latest will stay on alpine as it's the smallest possible build, but I've made changes to stop it breaking again in future. I'll try to get this finished this weekend.

**Comment by HariSekhon** [comment] 2017-01-13 22:06
You can now try Debian and Ubuntu tag versions which are now available while I continue to debug the Alpine package dependency conflicts.

**Comment by HariSekhon** [comment] 2017-01-13 22:08
The down side is that they're 268MB instead of 20MB (which is why I switched all my 40+ public containers in the first place).

Ultimately the improvements I'm making to the builds should prevent any more broken docker images due to upstream changes as they should fail better and not be accepting to the latest tag, but this is finished yet.

**Comment by Raboo** [comment] 2017-01-17 10:10
The end result isn't so much different, alpine 203 MB and Ubuntu 268 MB.

But don't misunderstand me, I like alpine linux and it's small size.
But if you add another rule to your automated build in docker hub
Type: Tag
Name: /^v([0-9.]+)$/
Docker Tag Name: [leave it blank I think].
So you will end up with two rules, one based on tags, and the default based on Branch master-latest rule.

Then you can create tags in GitHub with then name example v0.1.0, v0.1.1, etc..  Your docker hub automated build will create a tag with the name v0.1.0.
So that way if "latest" tag (master) breaks, people still have the option of downloading older versions like v0.1.0 from docker hub.

So every time you have made a change that is working, you add a tag in your repo with a new version.

**Comment by HariSekhon** [comment] 2017-01-19 19:38
I've put the latest image on debian for now.

I'll fix up the Alpine and CentOS builds later.

If you try again now it should be fixed.

**Comment by roaldle** [comment] 2017-01-20 16:00
I get the follow error when using the latest image

```
root@solr1:/var/docker/ca003# docker run --rm --net="host" harisekhon/nagios-plugins check_solr_core.pl -H localhost -P 8983 --core ca003
Can't locate JSON.pm in @INC (you may need to install the JSON module) (@INC contains: /github/nagios-plugins/lib /usr/local/lib/perl5/site_perl /usr/local/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl) at /github/nagios-plugins/lib/HariSekhonUtils.pm line 71.
BEGIN failed--compilation aborted at /github/nagios-plugins/lib/HariSekhonUtils.pm line 71.
Compilation failed in require at /github/nagios-plugins/check_solr_core.pl line 26.
BEGIN failed--compilation aborted at /github/nagios-plugins/check_solr_core.pl line 26.
```

**Comment by HariSekhon** [comment] 2017-01-20 16:20
Ok it looks like DockerHub didn't save the change I made to point to the debian branch and the automated build has overwritten it with the broken Alpine build.

I don't have access to the stuff I need from work but will try to remember to push the latest this weekend.

**Comment by HariSekhon** [comment] 2017-08-02 16:00
I believe this was resolved quite a long time ago and a CI check was added on it too, please re-open if necessary.

**Closed by HariSekhon** 2017-08-02 16:00 UTC
