### ISSUE TITLE
check_mysql_query.pl - invalid query defined: may only be a SELECT or SHOW statement

### ISSUE THREAD

**Issue by BadSanta79** [harisekhon/nagios-plugins#60] opened 2015-07-14 21:47 UTC
Hi, 

Great repo BTW. I am trying to use this plugin and am receiving the error "invalid query defined: may only be a SELECT or SHOW statement".

The query I am trying to run is below.

/usr/lib64/nagios/plugins/check_mysql_query.pl -H localhost -d DBNAME -q "select count(*) FROM EmailQueue WHERE status='PENDING' OR status='FAILED' OR status='NEW' AND scheduleDate is not null AND TIMESTAMPDIFF(MINUTE,NOW(),scheduleDate) <= 0;"

I've also tried the the command below, but had the same error.

/usr/lib64/nagios/plugins/check_mysql_query.pl -H localhost -d DBNAME -q "select count(*) from user;"

am I doing something wrong?

I cloned the repo today, so everything is up to date, and I performed the make operation and copied the lib folder.

Thanks so much

**Comment by harisekhon** [comment] 2015-07-14 22:26
Try taking the semi-colon out of the query. Btw this is mentioned in the ```--help``` description that while it works on the command line Nagios has issues with premature command termination due to the semi-colon that cannot be handled in code since it's raised by the shell before execution - you may end up with a null error outside of the scope of this code since it's before the plugin executes and adds handlers to catch everything.

I've just updated the underlying library to make the error more obvious that's it's caused by use of semi-colon which may end up causing Nagios errors so it'll be more intuitive for users to self correct their queries in future.

**Comment by harisekhon** [comment] 2015-07-15 15:26
@BadSanta79 

Did you try the update I just pushed to clarify the error and then try removing the semi-colon once notified by the more specific error message?

**Comment by BadSanta79** [comment] 2015-07-15 17:50
So very sorry for the delay. Yes, it does work without the semicolon. That is my mistake for not reading the help thoroughly. Thank you so much. Again, great work!

**Comment by harisekhon** [comment] 2015-07-15 19:02
Ok, I'll go ahead and close this ticket in that case.

**Closed by harisekhon** 2015-07-15 19:02 UTC
Labels: enhancement
