### ISSUE TITLE
check_krb5_kdc.pl realm underscore

### ISSUE THREAD

**Issue by Azef1** [HariSekhon/nagios-plugins#85] opened 2016-01-22 09:32 UTC
Hi,

For `check_krb5_kdc.pl`, if realm contain "_" (underscore), i get an error `invalid krb5 realm name defined`
i tested this command with -vvv.

Do you think it's a bug ?

Thx

**Comment by HariSekhon** [comment] 2016-01-22 09:53
This was by design since all the realms I have seen online and at all the companies I've worked for for over a decade are basically converted domain names.

Considering your case... if you can find me an official Kerberos realm naming doc I can update the validation to permit this.

**Comment by HariSekhon** [comment] 2016-02-19 09:49
@Azef1 

Do you still need to the krb5 realm validation extended? And if so can you supply a sample realm name or the list of characters that need to be supported?

**Comment by HariSekhon** [comment] 2016-03-23 17:21
@Azef1 

I'm going to close this ticket for now. You can re-open it if you still need it extended as long as I can get a clear rule for what the rule is for a valid Kerberos realm to be permitted, otherwise I'm going to leave it as the usual domain format realm, which doesn't include underscores.

Thanks

Hari

**Closed by HariSekhon** 2016-03-23 17:21 UTC
Labels: enhancement
