### ISSUE TITLE
Undefined subroutine &HariSekhonUtils::isObject

### ISSUE THREAD

**Issue by rmalenko** [harisekhon/nagios-plugins#75] opened 2015-11-19 16:32 UTC
Hello,

When I run ./check_redis_stats.pl -H localhost -P 6379 I got error
CRITICAL: Undefined subroutine &HariSekhonUtils::isObject called at lib/HariSekhonUtils.pm line 1020.

**Comment by harisekhon** [comment] 2015-11-19 16:40
Hi @rmalenko

I've just pushed a fix, please ```make update2``` and try again.

**Comment by rmalenko** [comment] 2015-11-19 16:50
Thank you. It looks now work.

```
./check_redis_stats.pl -H localhost -P 6379
OK: aof_current_rewrite_time_sec=-1 aof_enabled=0 aof_last_bgrewrite_status=ok aof_last_rewrite_tim
```
I have ran make update2
```
git pull
remote: Counting objects: 2, done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 2 (delta 1), reused 2 (delta 1), pack-reused 0
Unpacking objects: 100% (2/2), done.
From https://github.com/harisekhon/nagios-plugins
   e0791b9..80ddb32  master     -> origin/master
Fetching submodule lib
remote: Counting objects: 3, done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 3 (delta 2), reused 3 (delta 2), pack-reused 0
Unpacking objects: 100% (3/3), done.
From https://github.com/harisekhon/lib
   d7bbd94..c7764b1  master     -> origin/master
Updating e0791b9..80ddb32
Fast-forward
 lib | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
git submodule update --init
Submodule path 'lib': checked out 'c7764b11f8e3f5f33994d805aaa2f77a2335a7a9'
```

**Comment by harisekhon** [comment] 2015-11-19 17:03
Short version:

I'll close this ticket.

Long explanation if interested:

Actually that hasn't hit the same code path. The error you had was a problem raised from Redis but catch handler was using a piece of code that was commented out. This last run was a successful run so didn't hit the same code path. This is why it hasn't come up before because it would require creating a failure in the Redis server, although I've just added a test to try to provoke a similar failure.

The code is extremely defensively written though with buried hooks and handlers to enforce correct Nagios exit code and status prefix no matter what so it will still raise a CRITICAL to alert on if there is any issue at all (which is the most important bit from a monitoring perspective) but that bug of some of the code being commented out simply masked the root cause.

I'll close this ticket as it should be fixed now.

Thanks

Hari

**Closed by harisekhon** 2015-11-19 17:03 UTC
Labels: bug

**Comment by rmalenko** [comment] 2015-11-19 17:06
Thank you a lot!

I am studying the icinga and I am looking for how to monitor my servers. By this reason I work as tester:)
