### ISSUE TITLE
Can't locate object method "_init_conn" in check_mongodb_write.pl

### ISSUE THREAD

**Issue by IdahoPL** [harisekhon/nagios-plugins#46] opened 2015-03-23 11:23 UTC
$ git pull
Already up-to-date.

 $ ./check_mongodb_write.pl -H x.x.x.x -u user -p pass -d nagios
CRITICAL: failed to connect to MongoDB host 'mongodb://x.x.x.x': Can't locate object method "_init_conn" via package "MongoDB::MongoClient" at /usr/local/lib/perl5/site_perl/mach/5.18/MongoDB/MongoClient.pm line 354.

OS: FreeBSD 9.3
perl5-5.18.4_11
p5-MongoDB-0.708.0.0

**Comment by harisekhon** [comment] 2015-03-23 11:35
@IdahoPL 

I saw this once before but the guy never confirmed if any of the things we tried fixed it and I couldn't reproduce it on any of my systems which makes it difficult to fix without feedback.

Here is the only upstream library reference to this problem I could find:

https://jira.mongodb.org/browse/PERL-431

According to that MongoDB is required to bootstrap the internals but I do have use MongoDB at the top however. 

I've just added it to my lib as well just in case... please run

```make update```

and then try again.

If that doesn't work then try removing 'use MongoDB::MongoClient;' from check_mongodb_write.pl line  74 and possibly also lib/HariSekhon/MongoDB.pm line 24 and see if it helps (and please let me know).

Thanks

Hari

**Comment by IdahoPL** [comment] 2015-03-23 12:15
I've updated lib, that helped. Thank you.

**Comment by harisekhon** [comment] 2015-03-23 12:21
So was the fix running ``make update``` or did you have to also remove the MongoDB::MongoClient line from lib?

**Comment by IdahoPL** [comment] 2015-03-23 12:28
make update was enough, I didn't touch MongoDB::MongoClient line.

**Comment by harisekhon** [comment] 2015-03-23 12:33
Great, that means it should be fixed for everybody. I'll close this ticket then.

**Closed by harisekhon** 2015-03-23 12:33 UTC
