### ISSUE TITLE
certificate validation failed, returned 19 or 20 on Fedora Core / openssl 1.1.0h

### ISSUE THREAD

**Issue by romain-dartigues** [HariSekhon/Nagios-Plugins#205] opened 2018-09-20 09:23 UTC
Maybe it's related to @Twibow [comment](https://github.com/HariSekhon/nagios-plugins/issues/163#issuecomment-397607607) from #163.

I get either:
* CRITICAL: Certificate validation failed, returned 19 (self signed certificate in certificate chain)
* CRITICAL: Certificate validation failed, returned 20 (unable to get local issuer certificate)

**OS**: Fedora Core 27 (from Docker hub)
**OpenSSL version**: 1.1.0h-fips  27 Mar 2018
**Script version**: `check_ssl_cert.pl` @ b3cf13f
**Output scrubbed with**: `anonymize.pl` from HariSekhon/devops-perl-tools@06544f0 (+ `sed` to not stand up in some search...):
* `check_ssl_cert.pl -H github.com -P 443 -S github.com -vvv`: [github.log](https://github.com/HariSekhon/nagios-plugins/files/2400567/github.log)
* `check_ssl_cert.pl -H REDACTED.com -P 443 -S REDACTED.com -vvv`: [priv.log](https://github.com/HariSekhon/nagios-plugins/files/2400573/priv.log)

Not that I *don't* get the issue when I remove the `-CApath` option from the `openssl` command:
* `/usr/bin/openssl s_client -connect github.com:443 -servername github.com 2>&1 <<<echo`: [openssl-github.log](https://github.com/HariSekhon/nagios-plugins/files/2400591/openssl-github.log)
* `/usr/bin/openssl s_client -connect REDACTED.com:443 -servername REDACTED.com 2>&1 <<<echo`: [openssl-priv.log](https://github.com/HariSekhon/nagios-plugins/files/2400592/openssl-priv.log)

Nor when I specify `-CAfile` instead:
* `openssl s_client -connect github.com:443 -CAfile /etc/pki/tls/cert.pem -servername github.com 2>&1 <<<echo`: [openssl-cafile-github.log](https://github.com/HariSekhon/nagios-plugins/files/2400605/openssl-cafile-github.log)
* `echo | openssl s_client -connect REDACTED.com:443 -CAfile /etc/pki/tls/cert.pem -servername REDACTED.com 2>&1`: [openssl-cafile-priv.log](https://github.com/HariSekhon/nagios-plugins/files/2400603/openssl-cafile-priv.log)

**Comment by HariSekhon** [comment] 2019-03-19 08:49
This should be fixed now, it was caused by changing behaviour of openssl on Fedora's SSL CApath compared to CentOS and other distros where it was working.

If you `git pull` this should be solved for you.

You're welcome to re-open this issue if needed.

Thanks

Hari

**Closed by HariSekhon** 2019-03-19 08:49 UTC
