### ISSUE TITLE
/check_solr_metrics.pl usage issue

### ISSUE THREAD

**Issue by emirmandal** [HariSekhon/nagios-plugins#127] opened 2017-01-01 12:00 UTC
Hi,

when i use 
./check_solr_metrics.pl -H x.x.x.x -P 8080 -C collection1 -A QUERYHANDLER -K org.apache.solr.handler.dataimport.DataImportHandler -vvv

`UNKNOWN: no stats collected. Stats may be null or API may have changed.`

full output 
```
./check_solr_metrics.pl -H x.x.x.x -P 8080 -C collection1 -A QUERYHANDLER -K org.apache.solr.handler.dataimport.DataImportHandler -vvv
verbose mode on

check_solr_metrics.pl version 0.3.4  =>  Hari Sekhon Utils version 1.18.6

host:                     x.x.x.x
port:                     8080
collection:               collection1
category:                 QUERYHANDLER
http context:             /solr

setting timeout to 10 secs

querying Solr
HTTP GET http://x.x.x.x:8080/solr/collection1/admin/mbeans?stats=true&cat=QUERYHANDLER&key=org.apache.solr.handler.dataimport.DataImportHandler&omitHeader=off&wt=json&start=0&rows=3&indent=true
returned HTML:

{
  "responseHeader":{
    "status":0,
    "QTime":0},
  "solr-mbeans":[
    "QUERYHANDLER",{
      "org.apache.solr.handler.dataimport.DataImportHandler":{
        "class":"org.apache.solr.handler.dataimport.DataImportHandler",
        "version":"4.0.0.2012.10.06.03.04.24",
        "description":"Manage data import from databases to Solr",
        "src":"$URL: https://svn.apache.org/repos/asf/lucene/dev/branches/lucene_solr_4_0/solr/contrib/dataimporthandler/src/java/org/apache/solr/handler/dataimport/DataImportHandler.java $",
        "stats":[
          "Status","IDLE",
          "Documents Processed","java.util.concurrent.atomic.AtomicLong:60895",
          "Requests made to DataSource","java.util.concurrent.atomic.AtomicLong:174599",
          "Rows Fetched","java.util.concurrent.atomic.AtomicLong:275806",
          "Documents Deleted","java.util.concurrent.atomic.AtomicLong:0",
          "Documents Skipped","java.util.concurrent.atomic.AtomicLong:0",
          "Total Documents Processed","java.util.concurrent.atomic.AtomicLong:2922985",
          "Total Requests made to DataSource","java.util.concurrent.atomic.AtomicLong:8380777",
          "Total Rows Fetched","java.util.concurrent.atomic.AtomicLong:13324938",
          "Total Documents Deleted","java.util.concurrent.atomic.AtomicLong:0",
          "Total Documents Skipped","java.util.concurrent.atomic.AtomicLong:0",
          "handlerStart",1483116836701,
          "requests",1113,
          "errors",0,
          "timeouts",0,
          "totalTime",1253,
          "avgTimePerRequest",1.1257862,
          "avgRequestsPerSecond",0.0072036088]}}]}


http status code:     200
http status message:  OK

parsing output from Solr

UNKNOWN: no stats collected. Stats may be null or API may have changed. Please try latest version from https://github.com/harisekhon/nagios-plugins, re-run on command line with -vvv and if problem persists paste full output from -vvv mode in to a ticket requesting a fix/update at https://github.com/harisekhon/nagios-plugins/issues/new
```

for other categories/keys i have normal output 

`Linux Centreon-Central 2.6.32-642.11.1.el6.x86_64`

**Comment by HariSekhon** [comment] 2017-01-01 17:01
@emirmandal 

Thanks for raising this ticket.

The issue looks like it's caused by the Solr API returning the stats as an array instead of a hash, which was caught by a safety bit of code I added.

I've just pushed a fix, please `git pull` and try again and let me know.

Thanks

Hari

**Comment by emirmandal** [comment] 2017-01-02 09:47
Hi,
thank you very much
your fix is working. 
I fould one more key that is returning stats the same way as an array.

`./check_solr_metrics.pl -H 212.200.54.154 -P 8080 -C collection1 -A QUERYHANDLER -K /dataimport
UNKNOWN: no stats collected. Stats may be null or API may have changed.`

this is basically same key as `org.apache.solr.handler.dataimport.DataImportHandler`

so you fixed issue for me.

Than you for your quick response and providing solution.

Best regards,
Emir

**Comment by HariSekhon** [comment] 2017-01-02 10:59
I've just modified the fix to cover that as well. I'll go ahead and close this ticket. Feel free to re-open it if needed.

**Closed by HariSekhon** 2017-01-02 10:59 UTC
