### ISSUE TITLE
check_hadoop_dfs.pl balance check doesn't see all my datanodes?

### ISSUE THREAD

**Issue by gdubicki** [HariSekhon/nagios-plugins#162] opened 2017-07-15 12:00 UTC
We are running:

```
check_hadoop_dfs.pl  -b -w 20 -c 40 -t 60
```

..and getting:

```
WARNING: 22.39% block imbalance across 3 datanodes (22.39>20, w=20/c=40)
```

...and 1 minute later:

```
OK: 10.81% block imbalance across 2 datanodes
```

This happens many times every day.

I haven't dug into this so perhaps I misunderstand how this check works, but I am surprised to see 3 nodes first, then 2 as my cluster has 4 datanodes... Doesn't this indicate a problem with the check?

Also: is it possible that this flapping occurs because my datanodes hold very little amount of data?

```
Node | Last contact | Capacity | Blocks | Block pool used | Version
-- | -- | -- | -- | -- | --
c7-ci-eu-hdfs-datanode01.c.company.com (10.116.3.45:50010) | Sat Jul 15 13:46:36 +0200 2017 | 196.74 GB | 67 | 3.45 GB (1.75%) | 2.6.0-cdh5.9.0
c7-ci-eu-hdfs-datanode02.c.company.com (10.116.3.43:50010) | Sat Jul 15 13:46:35 +0200 2017 | 196.74 GB | 79 | 3.94 GB (2.01%) | 2.6.0-cdh5.9.0
c7-ci-eu-hdfs-datanode03.c.company.com (10.116.3.46:50010) | Sat Jul 15 13:46:34 +0200 2017 | 196.74 GB | 83 | 4.13 GB (2.1%) | 2.6.0-cdh5.9.0
c7-ci-eu-hdfs-datanode04.c.company.com (10.116.3.44:50010) | Sat Jul 15 13:46:35 +0200 2017 | 196.74 GB | 74 | 4.14 GB (2.1%) | 2.6.0-cdh5.9.0
```

**Comment by gdubicki** [comment] 2017-07-17 13:06
When I run this check manually I get 4 nodes in the output:

```
/etc/check_mk/scripts/cloudera/check_hadoop_dfs.pl  -b -w 20 -c 40 -t 60
OK: 0.30% HDFS imbalance on space used % across 4 datanodes | 'HDFS imbalance on space used %'=0.30%;20;40
```

**Comment by HariSekhon** [comment] 2017-07-18 08:11
Hi Greg,

Can you please paste the output with `-v -v -v` so that I can see the full debug output in each case?

Thanks

Hari

**Comment by HariSekhon** [comment] 2017-09-07 08:32
@gdubicki 

Where you able to run it with triple verbose mode to paste the output back here?

That way I can see what your environment looks like.

You can anonymize the output of addresses etc using `scrub.pl` from https://github.com/harisekhon/tools if needed.

**Comment by gdubicki** [comment] 2017-09-07 14:41
Hi @HariSekhon , sorry for a long delay in replying.

We currently think that this problem is caused by intermittent network issues within our Hadoop cluster which causes the check to sometimes see all the data nodes, and sometimes not.

I have tried to enable `-v` for now but that didn't gave me no info. I will try `-v -v -v` as you recommended now.

**Comment by HariSekhon** [comment] 2017-09-08 07:19
If this is a network problem with datanodes dropping in and out of the cluster you might be interested in a plugin I recently published (was on the backlog for ages) to check the last contact time of a given datanode to the namenode - `check_hadoop_datanode_last_contact.py`. This basically tells you if datanodes are not heartbeating properly to the namenode, which would result in them being dropped out of the list of datanodes and could explain your issue.

Additionally, for general network debugging I recommend you get SmokePing which continually monitors and graphs network packet loss on a network, it's been around for many years and wasn't hard to set up last I used it.

**Comment by gdubicki** [comment] 2017-09-08 13:00
I'll use this new check to verify this. Thanks!

**Comment by HariSekhon** [comment] 2017-09-12 08:41
@gdubicki 

Any luck with this so far? I'd like to be able to conclude whether this is actually a bug (`-v -v -v` output should help prove this either way) and am interested in your results using the new plugin too -typically the last contact per datanode should be very low number of seconds.

**Comment by HariSekhon** [comment] 2017-09-26 15:27
If you can't reproduce this then maybe we should close the ticket for now?

**Comment by HariSekhon** [comment] 2017-10-05 13:42
Closing ticket for now, please re-open if necessary.

Thanks

Hari

**Closed by HariSekhon** 2017-10-05 13:42 UTC
