### ISSUE TITLE
Fix for .eu whois nameserver parser

### ISSUE THREAD

**Issue by pbiering** [harisekhon/nagios-plugins#39] opened 2015-01-11 21:40 UTC
for .eu domains additional text is parsed as nameserver

domain: '$DOMAIN.eu'
registrant: 'NOT DISCLOSED!'
registrar: 'Vautron Rechenzentrum AG'
name server: '$NS1'
name server: '$NS2'
name server: 'please'
name server: 'visit'
name server: 'www.eurid.eu'
name server: 'for'
name server: 'more'

Fix: ignore the line

```
--- orig/check_whois.pl	2015-01-11 22:36:34.829182073 +0100
+++ check_whois.pl	2015-01-11 22:35:09.260154474 +0100
@@ -538,6 +538,7 @@
                 $no_nameservers_listed = 1;
                 last;
             } else {
+		next if ($line2 eq "Please visit www.eurid.eu for more info.");
                 foreach my $nameserver (split(/\s+/, $line2)){
                     next if(lc $nameserver eq "ns");
                     if(isHostname($nameserver) or isIP($nameserver)){
```

**Comment by harisekhon** [comment] 2015-01-11 22:17
@pbiering 

Thanks for raising this, I've created a slightly more generic version of this which also fixes the issue.

I'll close this issue since I've reproduced against google.eu and fixed successfully. Feel free to re-open should you have any more issues around this.

Best Regards,

Hari

**Closed by harisekhon** 2015-01-11 22:17 UTC
Labels: bug
