### ISSUE TITLE
check_solrcloud_cluster_status.pl -  Unknown 'core1.shards....' API may have change

### ISSUE THREAD

**Issue by thomas-wall** [HariSekhon/nagios-plugins#103] opened 2016-06-08 14:57 UTC
When i run the check from the Nagios server, it gives me the following information: 
This is from the latest version on github

```
./check_solrcloud_cluster_status.pl -H 'HostName' -P 8080 -C core1

UNKNOWN: 'core1.shards.shard1.replicas.xxxxxxxx.prod.tp4.shard1.node_name' 'xxxxxxxx' field not found. API may have changed. Please try latest version from https://github.com/harisekhon/nagios-plugins, re-run on command line with -vvv and if problem persists paste full output from -vvv mode in to a ticket requesting a fix/update at https://github.com/harisekhon/nagios-plugins/issues/new
```
**************************************************************************************
```
./check_solrcloud_cluster_status.pl -H 'HostName' -P 8080 -C core1 -vv

verbose mode on

host:                     solr.tp4.prod.mozu.com
port:                     8080
http context:             /solr
collection:               core1

setting timeout to 10 secs

querying Solr
http status code:     200
http status message:  OK

parsing output from Solr

collection 'core1':
                        shard 'shard1' state 'active'

UNKNOWN: 'core1.shards.shard1.replicas.xxxxxxxx.prod.tp4.shard1.node_name' 'xxxxxxxx' field not found. API may have changed. Please try latest version from https://github.com/harisekhon/nagios-plugins, re-run on command line with -vvv and if problem persists paste full output from -vvv mode in to a ticket requesting a fix/update at https://github.com/harisekhon/nagios-plugins/issues/new
```
**************************************************************************************
```
./check_solrcloud_cluster_status.pl -H 'HostName' -P 8080 -C core1 -vvv

verbose mode on

check_solrcloud_cluster_status.pl version 0.2.1  =>  Hari Sekhon Utils version 1.18.1

host:                     solr.FQDN.com
port:                     8080
http context:             /solr
collection:               core1

setting timeout to 10 secs

querying Solr
HTTP GET http://solr.FQDN.com:8080/solr/admin/collections?action=CLUSTERSTATUS&omitHeader=off&wt=json&start=0&rows=3&indent=true
returned HTML:

{
  "responseHeader":{
    "status":0,
    "QTime":24},
  "cluster":{
    "collections":{
      "core1":{
        "shards":{
          "shard1":{
            "range":"80000000-ffffffff",
            "state":"active",
            "replicas":{
              "Server1.prod.tp4.shard1":{
                "state":"active",
                "core":"Server1",
                "node_name":"xx.yy.zz.aa:8080_solr",
                "base_url":"http://xx.yy.zz.aa:8080/solr",
                "leader":"true"},
              "Server3.prod.tp4.shard1":{
                "state":"active",
                "core":"Server3",
                "node_name":"xx.yy.zz.cc:8080_solr",
                "base_url":"http://xx.yy.zz.cc:8080/solr"}}},
          "shard2":{
            "range":"0-7fffffff",
            "state":"active",
            "replicas":{
              "Server2.prod.tp4.shard2":{
                "state":"active",
                "core":"Server2",
                "node_name":"xx.yy.zz.bb:8080_solr",
                "base_url":"http://xx.yy.zz.bb:8080/solr"},
              "Server4.prod.tp4.shard2":{
                "state":"active",
                "core":"Server4",
                "node_name":"xx.yy.zz.dd:8080_solr",
                "base_url":"http://xx.yy.zz.dd:8080/solr",
                "leader":"true"}}}},
        "maxShardsPerNode":"1",
        "router":{"name":"compositeId"},
        "replicationFactor":"1",
        "autoCreated":"true"}},
    "live_nodes":["xx.yy.zz.aa:8080_solr",
      "xx.yy.zz.bb:8080_solr",
      "xx.yy.zz.cc:8080_solr",
      "xx.yy.zz.dd:8080_solr"]}}


http status code:     200
http status message:  OK

parsing output from Solr

collection 'core1':
                        shard 'shard1' state 'active'
UNKNOWN: 'core1.shards.shard1.replicas.Server1.prod.tp4.shard1.node_name' 'Server1' field not found. API may have changed. Please try latest version from https://github.com/harisekhon/nagios-plugins, re-run on command line with -vvv and if problem persists paste full output from -vvv mode in to a ticket requesting a fix/update at https://github.com/harisekhon/nagios-plugins/issues/new
```

Thanks

**Comment by HariSekhon** [comment] 2016-06-08 15:02
Since you're using dots in the node_name you need to escape those with a backslash otherwise they are used to descend the json and end up looking for a field called 'Server1' with subfield 'prod' etc instead of the 'Server1.prod.tp4'

**Comment by thomas-wall** [comment] 2016-06-08 15:06
im not quite sure what you mean "escape those with a backslash" are you referring to the check command itself

**Comment by HariSekhon** [comment] 2016-06-08 15:11
Hang on, I may have answered too quickly, usually this is related to needing to escape the dots in hostnames, but in this case it's inferring from the output, I'll reproduce this and get back to you shortly.

**Comment by HariSekhon** [comment] 2016-06-08 15:21
I've just pushed an update, please do a quick ```make update-no-recompile``` and retry.

**Comment by thomas-wall** [comment] 2016-06-08 15:54
not 100% sure what your talking about there honestly, relearning linux and these items

**Comment by HariSekhon** [comment] 2016-06-08 15:57
Simply updating the code should fix it for you.

You can run the command

```
make update-no-recompile

```
to quickly update the code without recompiling the cpan dependencies which would take a longer time.

Then re-running the plugin should work.

**Comment by thomas-wall** [comment] 2016-06-08 16:18
Now I get this:  Believe we are in business.  Thanks.. 

OK: all SolrCloud shards and replicas active for collection: core1, query time 136ms, QTime 26ms | query_time=136ms;;; query_QTime=26ms

**Comment by HariSekhon** [comment] 2016-06-08 16:20
Thanks for confirming, closing ticket.

**Closed by HariSekhon** 2016-06-08 16:20 UTC
Labels: bug
