### ISSUE TITLE
check_linux_interface.pl not working under CentOS 7

### ISSUE THREAD

**Issue by kotso** [HariSekhon/nagios-plugins#118] opened 2016-10-15 16:47 UTC
net-tools changed in centos 7 to version 2 and ifconfig output format now not same with previous version.

and check cant detect interface as cant parse ifconfig output.

also you have check for interface naming verifying that it's something like ethX but under CentOS 7 naming schema also changed, so I guess this check can be removed if interface specified exists in system.

**Comment by kotso** [comment] 2016-10-15 16:49
CentOS 7 ifconfig output

`eth4: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 1.2.3.4  netmask 255.255.255.0  broadcast 1.2.3.255
        inet6 fe80::92e2:baff:fe23:1a1c  prefixlen 64  scopeid 0x20<link>
        ether 90:e2:ba:23:1a:1c  txqueuelen 1000  (Ethernet)
        RX packets 110393986618  bytes 42482368321868 (38.6 TiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 219706126352  bytes 320720414950637 (291.6 TiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
`

CentOS 6 ifconfig output:

`eth0      Link encap:Ethernet  HWaddr 52:54:00:AE:24:9C  
          inet addr:1.2.3.4  Bcast:1.2.3.255  Mask:255.255.255.0
          inet6 addr: fe80::5054:ff:feae:249c/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:81240109 errors:0 dropped:0 overruns:0 frame:0
          TX packets:41127362 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:18767581288 (17.4 GiB)  TX bytes:40266346937 (37.5 GiB)
`

**Comment by HariSekhon** [comment] 2016-10-15 21:16
@kotso

Thanks for raising this issue.

This was on the backlog for quite a while but since you asked I've written a parsing update for it tonight, tested and pushed the fix for RHEL7's format change.

I'll close this issue for now but feel free to re-open it if needed.

Thanks

Hari

**Comment by kotso** [comment] 2016-10-16 11:20
@HariSekhon 

Thank you for that quick reply.

I'm checking now your updated version and still there is some bug.

    if(/^$interface\s+Link encap:(\w+)\s+HWaddr ($mac_regex)\s*$/){
        $encap = $1;
        $mac   = $2;
        $found_interface = 1;
        last;
    # RHEL7
    } elsif(/^$interface:\s+.*\smtu\s(\d+)\s*$/){
        $mtu = $1;
        $found_interface = 1;
    } elsif(/\bether\s+($mac_regex)\s+.*\((.+)\)\s*$/){
        $mac = $1;
        $encap = $2;
        last;
    }

RHEL 7 block to detect MTU never works. I guess something wrong with regexp but not strong enough to fix myself :)

**Comment by HariSekhon** [comment] 2016-10-16 15:30
I tested this on CentOS 7 on Docker and the updates worked as expected (there are reproducible dockerized tests in tests/test_linux.sh).

If you can run the plugin again with ```-v -v -v``` and send me the full output I'll have a look and see if I can provide a quick update.

Hari

**Comment by HariSekhon** [comment] 2016-10-16 16:47
I've just tested this on CentOS 7.0 and 7.1 on docker and it works on both of those too. I'll wait for your output.

**Comment by HariSekhon** [comment] 2016-10-20 11:38
@kotso 

Were you able to provide any more feedback on this such as the output from the plugin run?

If I can see the output I can provide the fix.

**Comment by kotso** [comment] 2016-10-21 07:09
Hi, 

Sorry for delay :)

Here is output:

```
verbose mode on

check_linux_interface.pl version 0.9.0  =>  Hari Sekhon Utils version 1.18.5

interface:                eth4
expected promiscuous mode: off

setting timeout to 10 secs

cmd: /sbin/ifconfig 2>&1

eth0: flags=4098<BROADCAST,MULTICAST>  mtu 1500
        ether 00:25:90:77:fd:e0  txqueuelen 1000  (Ethernet)
UNKNOWN: can't find interface 'eth4' in output from '/sbin/ifconfig' command

```

Brief about my system:

- it got multiple interfaces (from which some are down icluding eth0)
- on server i'm checking now interface names are renamed to classic centos schema ethX

**Comment by HariSekhon** [comment] 2016-10-21 08:50
Please try the latest version, let me know if this resolves it for you.

Thanks

Hari

**Comment by kotso** [comment] 2016-10-25 19:01
Just Tested.

Working on all my CentOS 7 installations (renamed interfaces, multiple
interfaces, etc...)

Thanks to much for your time and help :)

**Comment by HariSekhon** [comment] 2016-10-26 08:44
You're welcome, thanks for confirming, I'll close this issue now.

**Closed by HariSekhon** 2016-10-26 08:44 UTC
Labels: enhancement

**Comment by kotso** [comment] 2019-05-24 12:50
Hey,

I just signed the petition "Petition to the Nihon Sumo Kyokai" and wanted
to see if you could help by adding your name.

Our goal is to reach 1,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/dgsB25MmsK

Thanks!
Konstantine
