### ISSUE TITLE
SOLR 5.5

### ISSUE THREAD

**Issue by wdetter** [HariSekhon/nagios-plugins#89] opened 2016-03-23 08:26 UTC
Hi, 

I've just downloaded your plugins and tried to monitor SOLRCloud 5.5.0 Instances. I do get:

```
root@host01:/usr/src/nagios-plugins# ./check_solrcloud_cluster_status.pl  -H 10.10.1.42 -vvv
verbose mode on

check_solrcloud_cluster_status.pl version 0.2.1  =>  Hari Sekhon Utils version 1.18.1

host:                     10.10.1.42
port:                     8983
http context:             /solr

setting timeout to 10 secs

querying Solr
HTTP GET http://10.10.1.42:8983/solr/admin/collections?action=CLUSTERSTATUS&omitHeader=off&wt=json&start=0&rows=3&indent=true
returned HTML:

{
  "responseHeader":{
    "status":0,
    "QTime":5},
  "cluster":{
    "collections":{
      "test.core":{
        "replicationFactor":"2",
        "shards":{"shard1":{
            "range":"80000000-7fffffff",
            "state":"active",
            "replicas":{
              "core_node1":{
                "core":"test.core_shard1_replica1",
                "base_url":"http://host01:8983/solr",
                "node_name":"host01:8983_solr",
                "state":"active",
                "leader":"true"},
              "core_node2":{
                "core":"test.core_shard1_replica2",
                "base_url":"http://host02:8983/solr",
                "node_name":"host02:8983_solr",
                "state":"active"}}}},
        "router":{"name":"compositeId"},
        "maxShardsPerNode":"1",
        "autoAddReplicas":"false",
        "znodeVersion":70,
        "configName":"test.core"}},
    "live_nodes":["host02:8983_solr",
      "host01:8983_solr"]}}


http status code:     200
http status message:  OK

parsing output from Solr

collection 'test.core': 
UNKNOWN: 'test.core.shards' 'test' field not found. API may have changed. Please try latest version from https://github.com/harisekhon/nagios-plugins, re-run on command line with -vvv and if problem persists paste full output from -vvv mode in to a ticket requesting a fix/update at https://github.com/harisekhon/nagios-plugins/issues/new
```

Any Ideas? :) 

Thanks,
Werner

**Comment by HariSekhon** [comment] 2016-03-23 10:47
Hi Werner,

This is caused by the dot in the collection name conflicting with the child separator - it breaks the json traversal because it expects the first part to be "test", then child "core", then child "shards" and it doesn't find the first key "test". The usual way this is handled in this codebase is to escape the dot in the name.

I've done a generic fix to escape any dots in collection names for the relevant sub in the underlying library.

Please run ```make update-no-recompile``` and then try again.

Regards

Hari

**Comment by wdetter** [comment] 2016-03-23 11:11
Hi Hari, 

that was fast :) I've just ran `make update-no-recompile` and things are working now: 

```
OK: all SolrCloud shards and replicas active for collection: test.core, query time 48ms, QTime 5ms | query_time=48ms;;; query_QTime=5ms
```

Good job, thank you very much :+1: 
Werner

**Comment by HariSekhon** [comment] 2016-03-23 11:25
You're welcome :)

I'll go ahead and close this ticket as resolved.

**Closed by HariSekhon** 2016-03-23 11:25 UTC
Labels: bug, enhancement

**Comment by wdetter** [comment] 2016-03-23 11:48
Hi Hari,

just one more thing - I've just tried some more of the solr checkscripts where collection ist required.

```
root@nagios:#  /usr/lib/nagios/custom-plugins/nagios-plugins/check_solr_query.pl -H 10.10.1.42 -C test.core
CRITICAL: invalid Solr collection specified

root@nagios:#  /usr/lib/nagios/custom-plugins/nagios-plugins/check_solr_query.pl -H 10.10.1.42 --list-collections
Solr Collections:

test.core
```

```
root@nagios:# /usr/lib/nagios/custom-plugins/nagios-plugins/check_solr_metrics.pl -H 10.10.1.42 -C test.core
CRITICAL: invalid Solr collection specified

root@nagios:/usr/lib/nagios/custom-plugins/nagios-plugins#  /usr/lib/nagios/custom-plugins/nagios-plugins/check_solr_metrics.pl -H 10.10.1.42 --list-collections --list-categories
Solr Collections:

test.core
```

Could this also be an issue with the dot within the collection name? 

Cheers,
Werner

**Comment by HariSekhon** [comment] 2016-03-23 13:41
It is - I strictly validate all inputs to expected format and I hadn't permitted specifying dots in collection / core names hence the invalid collection name message.

I've now allowed dots in collection and core names in the underlying common library and checked the Solr plugins top level - only one needed additional escaping if permitting dots through the code.

If you ```make update-no-recompile``` and try again it should work now.

Thanks

Hari

**Comment by wdetter** [comment] 2016-03-23 13:57
Working like a charm - keep up the good work :+1: 

Thanks,
Werner
