### ISSUE TITLE
check_zookeeper.pl %mntr keys raises errors for negative return values (-1) for zk_min_latency

### ISSUE THREAD

**Issue by JulieSur** [harisekhon/nagios-plugins#51] opened 2015-05-20 20:45 UTC
During checks of the return values from %mntr configuration settings, the script exits when the returned config result from zookeeper host is negative.
In our case this was occurring for the following %mntr keys:
UNKNOWN: invalid value found for mntr zk_min_latency '-681​'

I am using zookeeper 3.4.5

**Comment by harisekhon** [comment] 2015-05-20 21:05
That's by design, I don't think it should be negative, seems like some sort
of error.

If we can explain why it occurs maybe I can handle it differently and raise
merely a warning...

On Wednesday, May 20, 2015, JulieSur <notifications@github.com> wrote:

> During checks of the return values from %mntr configuration settings, the
> script exits when the returned config result from zookeeper host is
> negative.
> In our case this was occurring for the following %mntr keys:
> UNKNOWN: invalid value found for mntr zk_min_latency '-681​'
>
> I am using zookeeper 3.4.5
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/harisekhon/nagios-plugins/issues/51>.
>


-- 
Best Regards,

Hari Sekhon
http://www.linkedin.com/in/harisekhon

**Comment by JulieSur** [comment] 2015-05-21 14:38
Thank you for prompt response. I am following up with the team to confirm what triggered this error.  Any specific information that you think will be helpful ?

**Comment by harisekhon** [comment] 2015-05-21 16:00
@JulieSur 

Running the plugin with -vvv for full debug output and pasting that in to this ticket would be helpful. If you don't want to expose your hostnames/ip addresses etc you can use scrub.pl on the output (I wrote it specifically for sanitizing sensitive hostnames/IPs from debug output) and it can be found here: 

https://github.com/harisekhon/toolbox

We need to try to figure out why the number for zk_min_latency is negative and what it means to decide if we want to change the behaviour accordingly. It may require some diving in to the ZooKeeper Java code to have a look at why it returns < 0. If the behaviour is explainable then we can make a call to have an exception for this case. I've already written the exception for it, but I'll only push it out if it makes logical sense.

**Comment by harisekhon** [comment] 2015-06-04 09:07
@JulieSur 

Can you provide any feedback why your setup is returning -681 for zk_min_latency? If not I'll close this issue as I can't create an exception for a behaviour that isn't well understood as the strictness of the code is specifically designed to alert on both known scenarios and unknown problems so that nothing should be missed by operations.

**Comment by harisekhon** [comment] 2015-06-04 22:29
@rexconsulting commented in https://github.com/harisekhon/nagios-plugins/issues/28 that this may be because the Java variable is wrapping around.

The question is, should we permit this as OK with N/A value for this metric? I already have a patch for that, but haven't decided if this is the right thing to do to push it publicly.

Do you see this happening consistently with ZooKeeper or is it temporary and then recovers?

**Comment by JulieSur** [comment] 2015-06-04 22:33
I have reached out to my team for confirmation on what information we can share to replicate the issue.
We saw it consistently for some time. We went ahead and ran  'srst' command against each Zookeeper node to resolve the issue.

**Comment by harisekhon** [comment] 2015-06-04 22:38
Maybe I should change the patch to tell users they will need to do the same to get the ZooKeeper stats back to sanity, but perhaps continue with the rest of the checks, filling this value with N/A and only raise a warning instead unless there are any other critical results...

**Comment by harisekhon** [comment] 2015-06-05 09:21
I've just pushed a fix to label the stat as N/A with warning message to reset the ZooKeeper stats via ```srst```.

The more I think about it the more this seems like a ZooKeeper bug and I've found this:

https://issues.apache.org/jira/browse/ZOOKEEPER-1922

Anyway, I think the latest update should handle it more gracefully. Try it out and let me know if I can close this ticket.

**Comment by harisekhon** [comment] 2015-06-13 21:05
@JulieSur I'll close this ticket for now, you can reopen it if needed.

**Closed by harisekhon** 2015-06-13 21:05 UTC
